#pragma once
#include "plex.h"
#include "discord.h"
#include "discord_ipc.h"
#include "models.h"
#include "config.h"
#include <iostream>
#include <thread>
#include <atomic>
#include <string>
#include <functional>
#include <csignal>
