#pragma once
#define DISCORDPP_IMPLEMENTATION
#include "plex.h"
#include "discord.h"
#include <iostream>
#include <thread>
#include <atomic>
#include <string>
#include <functional>
#include <csignal>
