#pragma once
#include "logger.h"
#include "plex.h"
#include "trayicon.h"
#include "discord.h"
#include "models.h"
#include "config.h"
#include <iostream>
#include <thread>
#include <atomic>
#include <string>
#include <functional>
#include <csignal>
#include <signal.h>
#include <iostream>
#include <string>
#include <thread>
#include <chrono>